### ISSUE TITLE
Get rtps_udp is not registered error OpenDDS 3.13 with static libraries

### ISSUE THREAD

**Issue by rcmcminn** [objectcomputing/OpenDDS#1003]
Test environment:
OS:       CentOS 7.5 64 bit
OpenDDS:       3.13

When I configure OpenDDS using all defaults (./configure), the make generates a set of shared object libraries. I generate my Makefiels using MPC. The two programs compile and link and run as expected.

When I remove the first installation and re-create OpenDDS with static libraries (./configure --static), the lib folder contains all archive libraries (.a). In order to get my applications to link, I muyst add "libs += rt to the MPC files to bring in librt.

The applications successfully link, but when I run, I get a segmentation fault in both. 

The INI file:
[common]
DCPSDebugLevel=0
DCPSTransportDebugLevel=0
DCPSGlobalTransportConfig=$file
DCPSDefaultDiscovery=DEFAULT_RTPS

[transport/the_rtps_transport]
transport_type=rtps_udp
thread_ptr_connection=1

Output from the subscriber application:
DS_INTERFACE_DEBUG=FALSE
DDS_CONFIG_FILE=ste_rtps.ini
Startup Parameters 
Arg 0  anonymous
Arg 1  -DCPSConfigFile
Arg 2  ste_rtps.ini
(7722|140055689033536) TransportRegistry::create_inst: transport_type=rtps_udp is not registered.
(7722|140055689033536) TransportRegistry::load_transport_configuration: Unable to create transport instance in [transport/the_rtps_transport] section.
(7722|140055689033536) ERROR: Service_Participant::load_configuration Unable to locate specified global transport config: ste_rtps.ini
(7722|140055689033536) ERROR: Service_Participant::get_domain_participant_factory: load_configuration() failed.

Once again, the publisher and subscriber application compile and work in the shared object environment; library reference for librt not needed, etc.

**Comment by mitza-oci** [comment]
When using static libraries, some translation unit of the application (typically the one containing `main`) needs to include the primary header file for the library so that the linker sees some use of it.  You can use `tests/DCPS/Messenger/publisher.cpp` as an example, but instead of including everything just include `<dds/DCPS/transport/rtps_udp/RtpsUdp.h>`.
Linking to librt is already handled by the makefiles that come with ACE and are included by the MPC-generated makefiles.  See `$ACE_ROOT/include/makeinclude/platform_linux.GNU`.

**Comment by rcmcminn** [comment]
I added the include referenced above. Once that was done, the "make" resulted in numerous undefined references to RTPS-related calls. To resolve this for the linker, I have to a the following lines to each MPC file

libs  += OpenDDS_Rtps
libs  += OpenDDS_Rtps_Udp

Now the two applications link again, but I am now getting a different error:

Service_Participant::load_discovery_configuration  Unable to load libraries for rtps_discovery

**Comment by rcmcminn** [comment]
Resolved the issue with an additional #include

#include <dds/DCPS/RTPS/Rtps_Discovery.h>

**Comment by mitza-oci** [comment]
Instead of manually maintaining lists of `libs +=` inside mpc files, make use of the base projects provided in the OpenDDS repository (in `$DDS_ROOT/MPC/config`).  That way if a future OpenDDS version changes the usage requirements for a library, your application projects will automatically be updated.
