### ISSUE TITLE
Configure with --no-tests still generates DevGuideExamples

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#1010]
I want only compile the OpenDDS core libraries with ACE+TAO, nothing more, so I am using --no-tests but the solution still contains all DevGuideExamples which I don't want. Why is --no-tests still generating projects for the DevGuideExamples, they are in all mwc files unconditionally.

**Comment by iguessthislldo** [comment]
It's technically correct since the examples aren't tests :wink:. Nevertheless, I've had the thought before that maybe there should be a seperate `--[no-]-examples` option for people who want the examples but not the tests. Thinking about it now though, I think that's why the DevGuideExamples are allowed in `--no-tests`.

**Comment by jwillemsen** [comment]
For integration within ROS2/AXCIOMA it would help to just have a workspace with only the core libs, hopefully at some point #595 gets implemented, that would reduce the dependencies further

**Comment by mitza-oci** [comment]
The DevGuideExamples are there to have something directly usable after `make` (see the Getting Started pages on opendds.org for example).  Since we can't anticipate every advanced use-case, you could add a `--workspace=` option to `configure`.  Because directories are also workspaces, `--workspace=dds` may get you close to what you need (perhaps with a few extra small libraries built).

**Comment by jwillemsen** [comment]
I will try to make a proposal next week

**Comment by vermaete** [comment]
IMHO, and  completely new to OpenDDS, have a --no-examples option to the config would be nice.
We would like to compile without tests, but with the iShapes demo.

**Comment by iguessthislldo** [comment]
@vermaete For that kind of scenario, I think what you would want is closer to what @mitza-oci suggested than what I suggested. You would have to pick out what you need in a custom workspace. You can do with OpenDDS as is if you know which mwc file is being used and change it. For example if you're using `--no-tests` and letting configure script get ACE/TAO (the default), then you could change `DDS_TAOv2.mwc` to:

```
workspace {
  // Keep all the $(ACE_ROOT) lines
  // Keep all the $(TAO_ROOT) lines
  dds
  examples/DCPS/ishapes
}
```

**Comment by iguessthislldo** [comment]
@jwillemsen @mitza-oci  In a lot of OpenDDS builds I modify `DDS_no_test.mwc`, like above to get `make` to build everything I want without worrying about what the targets are called, so I've been thinking about this for a while. I had a complicated solution to this a few weeks ago which would have involved configure getting more information from mpc, but the simple option I keep coming back to is manually specifying the workspace, like what Adam suggested. In addition to that I think it would be a good idea to have some sort of shortcut for adding ACE/TAO dependencies from `DDS_TAOv2.mwc` if configure is configuring ACE/TAO as well.

**Comment by mitza-oci** [comment]
@vermaete this is already supported
```
configure --tests
make ishapes
```
See README.md in the ishapes directory.

@iguessthislldo 
Use MPC workspace aggregation for this.  Let's open a new issue if we need to discuss further, or reopen this one.
