### ISSUE TITLE
Where is the executable ?

### ISSUE THREAD

**Issue by dimitri2705** [objectcomputing/OpenDDS#1077]
Hi !
Where is the compiled executable for Windows ?
It is very boring to download the softwares to be able to compile it...

**Comment by iguessthislldo** [comment]
It would be nice, but we don't have official prebuilt binaries of OpenDDS. [OpenDDSharp](http://www.openddsharp.com/) has unofficial builds to simplify using it if you want to use C#. If not and you have problems with building OpenDDS, we can try to help. We can't do much about it being boring unfortunately given the vast majority of software development is boring in one way or another.

**Comment by mitza-oci** [comment]
Some more background on why this works the way it does...

You can't do anything useful with the code in OpenDDS on its own.  It's a middleware framework for building your own distributed applications using the DDS standard.  Since you'll need to compile your own application with the same compiler version and options, the safest way to do this is for you to build OpenDDS from source.

Downstream projects/organizations can standardize on particular platforms/compilers/options and package up the development environment using tools of their choice, but that's beyond the scope of what we're doing in the OpenDDS project itself.  We have examples of using Docker for this.
