### ISSUE TITLE
DataWriterQos and TopicQos Reliability Should be Immutable

### ISSUE THREAD

**Issue by yuxuchang** [objectcomputing/OpenDDS#1131]
```C++
bool Qos_Helper::changeable(const DDS::DataWriterQos& qos1,
                            const DDS::DataWriterQos& qos2)
{
  return
    changeable(qos1.durability, qos2.durability)
#ifndef OPENDDS_NO_PERSISTENCE_PROFILE
    && changeable(qos1.durability_service, qos2.durability_service)
#endif
    && changeable(qos1.deadline, qos2.deadline)
    && changeable(qos1.latency_budget, qos2.latency_budget)
    && changeable(qos1.liveliness, qos2.liveliness)
    && changeable(qos1.destination_order, qos2.destination_order)
    && changeable(qos1.history, qos2.history)
    && changeable(qos1.resource_limits, qos2.resource_limits)
    && changeable(qos1.transport_priority, qos2.transport_priority)
    && changeable(qos1.lifespan, qos2.lifespan)
    && changeable(qos1.user_data, qos2.user_data)
    && changeable(qos1.ownership, qos2.ownership)
#ifndef OPENDDS_NO_OWNERSHIP_KIND_EXCLUSIVE
    && changeable(qos1.ownership_strength, qos2.ownership_strength)
#endif
    && changeable(qos1.writer_data_lifecycle, qos2.writer_data_lifecycle);
}
```

Why does this function not check whether `DataWriter`'s `ReliabilityQosPolicy` is changeable?

**Comment by iguessthislldo** [comment]
After looking into this, since reliability isn't changeable, it would seem that it should be checking. It is checking in `changeable(DDS::DataReaderQos, DDS::DataReaderQos)` so It looks like a small oversight of the original author since it looks like it's always been like this since it was changed from just  returning `qos1 == qos2`. Could you submit a pull request with the added check in `changeable(DDS::DataReaderQos, DDS::DataWriterQos)` and `changeable(DDS::TopicQos, DDS::TopicQos)` if it's missing the check too?

**Comment by yuxuchang** [comment]
Yes，changeable(DDS::TopicQos, DDS::TopicQos) also miss the check of reliability.
