### ISSUE TITLE
DCPSInfoRepo> exited with signal 4

### ISSUE THREAD

**Issue by agenteph** [objectcomputing/OpenDDS#1183]
I was able to configure it according to the tutorial for raspberry Pi, my model is PI 2.

All normal, until you send the files to the raspberry and run run_test.pl, I received the message below:

/home/pi/OpenDDS-3.13.2/build/target/bin/DCPSInfoRepo -ORBDebugLevel 10 -ORBLogFile DCPSInfoRepo.log -o repo.ior
ERROR: waiting for Info Repo IOR file
ERROR: </home/pi/OpenDDS-3.13.2/build/target/bin/DCPSInfoRepo> exited with signal 4 : ILL

Can someone help me please???

**Comment by agenteph** [comment]
Someone can help...?

**Comment by iguessthislldo** [comment]
According to [signal(7)](http://man7.org/linux/man-pages/man7/signal.7.html), `SIGILL` is an illegal instruction, which suggests it the wrong kind of ISA (that or something went wrong during the build or copy). Even though it says target in the path, are you sure that it's not an x86 version of `DCPSInfoRepo`? On the pi can you run `file /home/pi/OpenDDS-3.13.2/build/target/bin/DCPSInfoRepo`? It will say what the architecture is.

**Comment by agenteph** [comment]
According to the manual at:

http://opendds.org/quickstart/GettingStartedPi.html

Even though it says target in the path, are you sure that it is not an x86 version of DCPSInfoRepo?

A: It says the ubuntu version can be x86_64, the same one I used (ubuntu-18.04.2-live-server-amd64 and in PI I used the version at https://downloads.raspberrypi.org/raspbian_full_latest).

On the pi can you run file /home/pi/OpenDDS-3.13.2/build/target/bin/DCPSInfoRepo?

A: Well, looking for the file "DPCSInfoRepo", I could not find it. But in the message says it did not find the IOR file, suggesting that the file was not found.

During the compilation no error was shown that I have seen. I used the version with DDS Security. All compilations were OK. In the test with Java gave the same error.

What can it be? Need help.

**Comment by agenteph** [comment]
Another thing... My PI is version 2 B+.

Update and upgraded.

I need to install on him the requeriments like g++, gcc, perl and build-essential packets?

**Comment by iguessthislldo** [comment]
Let me try to rephrase what I said: I think OpenDDS was built wrong somehow and it can't run on the Pi.  The ILL signal is saying that the Pi can't run `DCPSInfoRepo` in the target directory, which means the whole target directory was likely built with the wrong compiler.

> On the pi can you run file /home/pi/OpenDDS-3.13.2/build/target/bin/DCPSInfoRepo?
>
> A: Well, looking for the file "DPCSInfoRepo", I could not find it. But in the message says it did not find the IOR file, suggesting that the file was not found.

I think you misunderstood what I meant. I want you to run this exact shell command on the Pi and tell me what it says:

```
file /home/pi/OpenDDS-3.13.2/build/target/bin/DCPSInfoRepo
```

`file` is a Linux command that prints out information about files, and will say if a program can run on a Pi by saying it's for ARM or run on a PC by saying it's for x86_64. You can ignore the IOR file message because `DCPSInfoRepo` should have made that.

> I need to install on him the requeriments like g++, gcc, perl and build-essential packets?

No, if you're following the guide, you shouldn't need g++ on the Pi, just on the host computer. Also perl is already there or else you wouldn't be able to run the `run_test.pl` perl script in the messenger example.

If you can't get the Pi guide to work for you, you can also build OpenDDS on the Pi if you want to like in #1135. What you can do is make sure `build-essential` is installed on the Pi and follow http://opendds.org/quickstart/GettingStartedLinux.html and use `./configure --no-tests` to speed up the build.

**Comment by agenteph** [comment]
I run the command you ask, the result:

**# file /home/pi/OpenDDS-3.13.2/build/target/bin/DCPSInfoRepo** 
/home/pi/OpenDDS-3.13.2/build/target/bin/DCPSInfoRepo: symbolic link to ../dds/InfoRepo/DCPSInfoRepo

Ok... so i use the command again... because its a symbolic link... :

**# file dds/InfoRepo/DCPSInfoRepo** (original file)
dds/InfoRepo/DCPSInfoRepo: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, with debug_info, not stripped

> dds/InfoRepo/DCPSInfoRepo: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, with debug_info, not stripped

**Comment by agenteph** [comment]
#1135 nice..., so can I do it right on the PI?

**Comment by iguessthislldo** [comment]
> because its a symbolic link... :

Sorry, forgot that it's a symlink...

> dds/InfoRepo/DCPSInfoRepo: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, with debug_info, not stripped

Hmmm, so it is an ARM executable, weird. There must be something wrong with it for the CPU to reject an instruction and create the ILL signal, but I'm not sure what.

> #1135 nice..., so can I do it right directly on the PI?

Yes, it'll just take longer to build it on the Pi than on a PC. I would recommend you try it though since  the Pi guide is producing weird results for you.

**Comment by agenteph** [comment]
Ok, really thanks @iguessthislldo.

Since last night, and have been compiling in the IP for 5 hours and counting. I using the link: http://opendds.org/quickstart/GettingStartedLinux.html

It really takes a lot of time. I'm working on a project for master's degree using IoT.

I had already run it on a virtual machine with Ubuntu Server 18.04 and it was all normal. We are now working on IP. It will work. Anything I write here again.
