### ISSUE TITLE
Change retcode_to_string to return a const char* so that it can be easily logged using %C

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#1188]
Currently it returns a OPENDDS_STRING which is more costly and we have to use .c_str() on it, see https://github.com/DOCGroup/CIAO/blob/master/connectors/dds4ccm/impl/Utils.h for how DDS4CCM does this

**Comment by iguessthislldo** [comment]
That won't work as the function is written now, because it allows for reporting if a retcode is invalid and reports what the retcode value is. If the retcodes were an actual type like a `enum class` I would have gone with `const char *`.

**Comment by iguessthislldo** [comment]
Actually I guess the error message would take care of reporting the invalid value...

**Comment by iguessthislldo** [comment]
If we do change this, this would also apply to `InstanceState::instance_state_string()`, which I also created. Also maybe it should be pull out of `InstanceState` and put in `SafetyProfileStreams.h` as well. There might be more of these kind of enum-like to string type functions in OpenDDS, but I'm not sure. This is really something that should be built into the language, like `@memberName` in [zig](https://ziglang.org/documentation/0.4.0/#enum).

**Comment by mitza-oci** [comment]
Is there consensus on what this should be doing?  The CIAO example doesn't support reporting what the value actually was when it was unknown, but not sure how much we need that.

**Comment by iguessthislldo** [comment]
> Is there consensus on what this should be doing?

I think me and Johnny agree that these functions should exist and it should report when they get an invalid value. I'm just not sure how much of a performance hit we're taking from using `std::string` to report the value directly. I know it costs something vs fixed c strings, but if this function is already running that means we're debug logging and so we're already taking a hit for that.

> The CIAO example doesn't support reporting what the value actually was when it was unknown, but not sure how much we need that.

I think it's useful. When working on #1067, instances were set up wrong with unions and because I could see that instance state was 0, I was quickly led to the instance state not being set up correctly.

**Comment by mitza-oci** [comment]
Since it's a fixed (maximum) size, it could provide a local buffer:
```
if (something failed) {
  char msg[EXTENDED_LOG_MAX_SIZE];
  LOG("format str %C%C\n", retcode_to_string(ret, msg), msg);
}
```
with the 2nd parameter to `retcode_to_string` being optional.

But again, I'm not sure how extensive we want to go here.  The example of #1067 is an interesting one, but during development once you see an error for "unknown value" it may be better to go with valgrind/asan or a debugger.

**Comment by iguessthislldo** [comment]
> There might be more of these kind of enum-like to string type functions in OpenDDS, but I'm not sure.

Apparently I really like making these things because I found another one I made to add to the list: `Sedp::Msg::msgTypeToString` in `dds/DCPS/RTPS/Sedp.cpp`.

**Comment by iguessthislldo** [comment]
Already I guess we're doing this then. List of functions to change that I have accumulated so far:

- `retcode_to_string`
- `InstanceState::instance_state_string()`
- `WriterInfo::get_state_str()` in `dds/DCPS/WriterInfo.cpp`
- `Sedp::Msg::msgTypeToString` in `dds/DCPS/RTPS/Sedp.cpp`

I will change them to use `const char*` and make sure all of them return something like `<Invalid Value>` and make an appropriate error message when an invalid value is passed.

**Comment by mitza-oci** [comment]
Can this be closed?

**Comment by iguessthislldo** [comment]
Yes, I think so.
