### ISSUE TITLE
Using Arbitrary Data

### ISSUE THREAD

**Issue by AyalaIsakov** [objectcomputing/OpenDDS#1208]
if for example i have an idl with this message:

```
typedef long IntArray[10];
struct foo{
  long x;
  double y;
  string z;
  IntArray array;
};
```

i have a program that use her own data to send the messages. The input is the idl.. 
Do you guys think that i can change the message `foo` structure to just be a very big buffer and it will still work? The spread of the messages will be in the other program...
Does it really need the `x`, `y`, `z`, and `array` fields?

**Comment by iguessthislldo** [comment]
I edited your example to be correct IDL that OpenDDS would accept.

Assuming you're handling serialization properly, yes you can just make the data arbitrary bytes and handle serialization yourself. I wouldn't make them "very big" though because OpenDDS still has to transport the data. Use octet arrays if you know the data is always going to be a certain size, otherwise octet sequences. However, as a warning, if you're forgoing using the proper IDL serialization you won't be able to take advantage of features of OpenDDS that require it to know how to read your data such as DDS instances and queries/filtering.

**Comment by AyalaIsakov** [comment]
Thank you very much! :)
