### ISSUE TITLE
cmake OPENDDS_TARGET_SOURCES polluting global includes

### ISSUE THREAD

**Issue by joeroback** [objectcomputing/OpenDDS#1395]
`OPENDDS_TARGET_SOURCES` macro seems to pollute the global (directory) includes, moreover, it does not include the headers as "system" headers, so tools like `clang-tidy` include them (`clang-tidy` will ignore system headers with the right option), and my project's `clang-tidy` rules are being applied to the IDL generated headers.

I am not even sure why `opendds_include_dirs_once()` exists in the first place, when all the other options on the target use `target_compile_definitions` and `target_link_libraries`, why not use `target_include_directories`?

**Comment by mitza-oci** [comment]
I don't think I can answer the question "why not use...?" but please go ahead with a pull request to make this change.

**Comment by mitza-oci** [comment]
It looks like there are 2 distinct issues:

1. `opendds_include_dirs_once` doesn't need to be there, the function and the 1 place it's called can just be removed

2. The use "system" include paths could be configured by a CMake cache variable in order to give the end user control of this.  If I'm reading your comment correctly, this refers to header files generated by the IDL compilers and not header files that come with OpenDDS.  If so, I believe this is handled around lines 50-55 of `dds_idl_sources.cmake`.  The new cache variable could be used to determine if an extra `SYSTEM` argument is passed to `target_include_directories`.  One potential drawback is that the use of "system" includes may impact dependency tracking on certain platforms/buildsystems.

@joeroback please confirm if this will indeed fix the issue and let us know if you can create a pull request for one or both

**Comment by joeroback** [comment]
correct for 1, for 2, not sure what to say, if you use tools like clang-tidy + cmake, if the headers are not marked as "system", clang-tidy will run over those headers and of course they do not follow so arbitrary coding standard that the project is using, so clang-tidy hates them. SYSTEM flag does change `-I` to `-isystem` and while that does change the behavior of how the compiler handles them, I have no experienced issues with generated headers being included as `-isystem` ... at least this project is windows / linux x86, and cross-compile linux aarch64 .. but that is not every system out there...

**Comment by mitza-oci** [comment]
OK, I'm fine with an end-user configurable (CMake cache variable) for the SYSTEM flag.
Another approach would be to build a separate library containing just the generated code and don't run clang-tidy on it.

**Comment by joeroback** [comment]
oh yea, i didn't think about making a separate cmake target and disabling tidy on that target.. seems cleaner to me, if like you said, `SYSTEM` could impact dependency tracking on certain platforms/buildsystems

**Comment by iguessthislldo** [comment]
Did I fix this in #1741?

**Comment by iguessthislldo** [comment]
It looks like ACE/TAO/OpenDDS library includes are using `-isystem` now, but IDL generated includes are still using `-I`.

**Comment by iguessthislldo** [comment]
Revisiting this, I think the way the includes work are probably acceptable for now and the most egregious include issue was fixed, so I think we can close this.
