### ISSUE TITLE
Question: possible to run tests in parallel?

### ISSUE THREAD

**Issue by mouse07410** [objectcomputing/OpenDDS#1514]
Currently,  when I run all the tests specified here
```
   time $ACE_ROOT/bin/auto_run_tests.pl \
      -d \
      $DDS_ROOT/tests/security/security_tests.lst \
      $DDS_ROOT/java/tests/dcps_java_tests.lst \
      -Config RTPS -Config NO_SHMEM -Config DDS_NO_ORBSVCS -Config CXX11 \
      2>&1 | tee tests-long-out-${DAT}.txt
```
on a reasonably fast 12-core machine (with a lot of RAM ;), it takes about an hour and a half to complete.

I wonder if it's possible to run (some?) tests in parallel - and if so, how?

Thanks!

**Comment by mitza-oci** [comment]
It is not possible because the tests depend on using port numbers that may conflict with other tests.  With `-Config RTPS` there is a dependency on multicast participant discovery so cross-talk between tests would be problematic.

We have done some prototyping on ways to overcome some of these issues, but the results of that are not in the repo at the moment.  Let us know if you'd like to collaborate on it and we can find what was done previously.

**Comment by mouse07410** [comment]
>  Let us know if you'd like to collaborate on it and we can find what was done previously...

Sorry. I'd love to - but I'd never get approval to contribute to that effort. :-(
I appreciate the invitation collaborate though!
