### ISSUE TITLE
WARNING: Could not find FQDN. 

### ISSUE THREAD

**Issue by JessieTang2018** [objectcomputing/OpenDDS#1567]

**Comment by iguessthislldo** [comment]
Test

**Comment by iguessthislldo** [comment]
Okay I can write comments now? Okay so:

1. This warning log message just says that the computer doesn't have a DNS name and that's okay. Googling "FQDN" will provide you with more information.
2. I don't know if this is Github messing up, because I couldn't comment at all just a little while ago, but you don't have a description on this issue. In the future please at least give a sentence describing your issue. This just doesn't go for this repository or Github in general, but anywhere on the internet.
