### ISSUE TITLE
Are the latency statistics accurate?

### ISSUE THREAD

**Issue by KiriakosD** [objectcomputing/OpenDDS#1796]
I have been running some tests connecting two machines. One is running a writer (writing 1000 messages, 1 every ~100ms) and one is running a reader (and also keeps the latency statistics).
I tried to get some latency measurements when connecting the two machines over wifi(using  a Netgear Router), and over Ethernet (using  a Netgear Switch).

I am using the default QoS and the rtps.ini in both looks like this:
```
[common]
DCPSDefaultDiscovery=DEFAULT_RTPS
DCPSGlobalTransportConfig=$file

[transport/the_rtps_transport]
transport_type=rtps_udp
use_multicast=0
```

I was expecting to find a big difference in the latency, but to my surprise, it was not that big (in fact the latency over Ethernet seemed a bit higher).

**Over Ethernet**
```
stats[0]:
 n = 779
 max = 0.337942
 min = 0.336865
 mean = 0.337139
 variance = 1.31089e-08
```
**Over WiFi**
```
stats[0]:
 n = 997
 max = 0.322761
 min = 0.316243
 mean = 0.317261
 variance = 1.73326e-06
```

The lost messages seemed to vary a lot from test to test and what I have noticed in general the biggest loss is usually in the beginning (I assume due to a slow discovery?), when I start running the applications and especially when I run the reader first the writer second.

Do you know why might that be? And if there are any ways to improve it?
Could it be that somehow the latency statistics measurements are not accurate?

PS
I assume the latency measurements are in seconds, right?

**Comment by simpsont-oci** [comment]
I'm going to assume you're using the latency statistics from DCPS::DataReaderImpl::get_latency_stats() and not from one of our performance tests.

In that case, yes, it's seconds. One of the disadvantages of using purely reader-side latency calculations like DCPS::DataReaderImpl::get_latency_stats() is that if you're testing on two different machines you will inadvertently add or subtract the clock skew between your machine into the latency calculation.  Even using a mechanism like NTP to synchronize system time between your machines will only let you get as accurate as however closely synced your two machines are to network time. In particular, for Windows 10, the last I checked it seems like Windows would only sync to network time once a day, allowing for a relatively large clock skew between machines. A more accurate way of measuring latency between two machines is to halve the round-trip latency, which our performance tests will do when correctly configured.

As for the dropped packets, I would need to know more about your test applications. In general, if you only have one reader and one writer and you don't want to miss any initial packets, you can always delay your writes until the publication matched status is updated to show the matched reader. For a relatively naive way of doing this, see tests/DCPS/LatencyBudget/Writer.cpp where it waits for publication_matched() to be true. For a slightly more robust way of doing it, you can look at using something like Utils::wait_match() from tests/Utils/StatusMatching.h where it waits for a particular number of matches. Also worth noting that even if you delay, you can inadvertently write packets early by matching against other compatible readers that happen to be discoverable on your network. You can use QoS settings like partition in order to combat this if it's an issue for your setup.

**Comment by KiriakosD** [comment]
Thanks a lot @simpsont-oci!
Yes we are using the DCPS::DataReaderImpl::get_latency_stats()
After started using the publication matched, the loss looks much more reasonable.

In our application the goal is to share the status of autonomous vehicles every x milliseconds. If the message is not send in this timeframe, it might as well be discarded as the status has already changed.

I thought about the idea of halving the round-trip latency, but I was not sure what's the best way to implement it. How do you do it in your performance tests?
At the moment everything we do is synchronous, using 100ms cycles. That means that when the writer thread has it's time slot, it uses the write function, and when the reader thread has its slot, it uses the take function.

![loss](https://user-images.githubusercontent.com/8714981/87858526-cb9d8c80-c92e-11ea-8b3d-b2c4fea99cd4.png)


![mean_latency](https://user-images.githubusercontent.com/8714981/87858532-d526f480-c92e-11ea-821e-83f6b88cf2e4.png)
