### ISSUE TITLE
OpenDDS versions 3.13 and 3.14 compatibility

### ISSUE THREAD

**Issue by Hadrian44** [objectcomputing/OpenDDS#1813]
Hello,
I am wondering about the compatibility between versions of OpenDDS.  For example, if I publish a message using version 3.13, can that message be successfully received by a subscriber running version 3.14?  I understand that the IDL file formats are different between these two versions, but assume that both sides use the same IDL file with the appropriate #pragma and `@topic` and `@key` entries.  Is there anything under the hood in OpenDDS that would cause a problem in this scenario?  Are there any adjustments that would be required for it to work?

I have searched for an answer to this question, but have not found anything that addresses it directly.

**Comment by mitza-oci** [comment]
In general, yes they are compatible.  What transport(s) and discovery configuration are you using?

Since all RTPS 2.x implementations are designed to be compatible, and OpenDDS 3.13 participant configured for RTPS discovery and the rtps_udp transport is compatible with a similarly-configured OpenDDS 3.14.

Although all 2.x protocol versions are intended to be interoperable, there have been breaking changes to fix errors in the spec.  Due to this, take a look at the RTPS 2.4 changes listed in the NEWS.md file, especially #1374.

**Comment by Hadrian44** [comment]
We are using rtps_udp transport without multicast.  Discovery is specified as DCPSInfoRepo with a network IP address and port number, and rtps_discovery lists SedpMulticast as 0.  The publisher side does not define an rtps_discovery lease duration (not available in 3.13?) but the subscriber side does.

I looked at NEWS.md and #1374, but I am not familiar enough with the OpenDDS code to be able to assess whether or not these bugs are an issue or not.

**Comment by mitza-oci** [comment]
There is that one difference in #1374 on how alignment is handled.  It changed in the RTPS 2.3 spec version.  If this is an issue, make sure to set the `DCPSRTISerialization` option to "on" in 3.13.  It's always on in 3.14.
If you have specific problems with interoperability please post an issue here.
