### ISSUE TITLE
Mean latency is going down the more writers we have

### ISSUE THREAD

**Issue by KiriakosD** [objectcomputing/OpenDDS#1864]
We are collecting the reader statistics and for some strange reason, it seems that when using default QoS, the mean latency is going down the more writers (interfaces) we are adding... The same pattern was observed when using RTPS UDP, Shared Memory and TCP. In the case of TCP the loss was 0, so I am having a very hard time understanding why is that...

PS 1
In the graph above the measurements for TCP are up to 20 writers
Every writer, writes 2000 times and then stops.

PS 2
The way I calculated the plot was by taking all the instances for each case and calculate the average.

PS 3
When using Reliable as Reliability QoS the mean is going up.

PS 4
Some raw values for the TCP are:

**1 writer**
stats[0]:
 n = 2000
 max = 0.001514
 min = 0.000288
 mean = 0.00035842
 variance = 2.83839e-09

**20 writers**
stats[0]:
 n = 2000
 max = 0.009548
 min = 6.1e-05
 mean = 0.000251802
 variance = 5.0226e-08
stats[1]:
 n = 2000
 max = 0.003048
 min = 6.1e-05
 mean = 0.00022668
 variance = 1.08606e-08
stats[2]:
 n = 2000
 max = 0.014934
 min = 6.2e-05
 mean = 0.000224303
 variance = 1.1553e-07
stats[3]:
 n = 2000
 max = 0.0023
 min = 6.1e-05
 mean = 0.000219841
 variance = 7.98632e-09
:
:

![118519219_598047974219792_3382736543708095737_n](https://user-images.githubusercontent.com/8714981/91878729-06117d80-ec80-11ea-823b-797827a657c5.png)

**Comment by simpsont-oci** [comment]
There could be a number of reasons for this, but without seeing your code it's difficult to give an educated guess as to why.

Are your writers in separate processes or just one. Are they using the same transport instance, or different instances? Are they writing to the same sample instance, or different instances? What are your other QoS settings? In particular, what are your history and resource limit QoS settings?

If the first few samples have a larger latency due to setup costs, then I would expect the average latency to go down the more samples get sent. And since it sounds like this is for best-effort, it's possible you're dropping packets that would have increased your mean latency.

Overall, I don't really see an issue that needs to be addressed, just an odd quirk of your test code and the stats gathering process. Do you agree?

**Comment by KiriakosD** [comment]
Thanks for your reply @simpsont-oci!

1. All the writers are running in separate threads and publish every 100ms until they publish 2000 times.
2. They all use the same transport instance.
3. They are writing in the same topic, but from the statistics I see that there are different instances.
4. The default QoS is used in all the entities.
5. The testing code is generally speaking very simple. With an x amount of writers (publishing every 100ms) and 1 reader (reading every 100ms). The way the tests were performed were a) start the application with x writer(s), b) let the writer(s) publish 2000 times, c) give it a few seconds margin and stop the application. d) start application with x+1 writers... etc until we reach 40 writers.


I think the setup cost could be the one to explain this. Initially I thought that the loss might also play a big part in this, but when I checked the results I saw that TCP has no loss at all, RTPS UDP has some loss, but only after the number of interfaces is higher than 11 and the Shared Memory has some loss only after the number of interfaces is higher than 27.

Thanks again for the suggestion, and if anything else comes to mind, let me know :)

For the record, here is the graph when comparing the latency between with different reliability and history QoS combinations:
