### ISSUE TITLE
Support for piggy-backed heartbeats and push mode in reliable QoS settings

### ISSUE THREAD

**Issue by luigima** [objectcomputing/OpenDDS#2032]
I am referring to the DDS Interoperability Wire Protocol / DDSI-RTPS specification  (https://www.omg.org/spec/DDSI-RTPS/2.3/PDF):

- Section 8.4.15.4 states the possibility of piggybacking heartbeat submessages. This method may reduce networking traffic, especially in scenarios where a datawriter is publishing data in fixed time intervals. 
I am aware that Section 8.4.15 is not part of the formal specification of the protocol but I wonder if OpenDDS supports it or will implement it in future versions.

- Table 8.47 specifies the attribute "pushMode" which, when enabled, will push data directly to the reader instead of announcing it with heartbeats. While this seems to be the default behavior in best-effort delivery, I wonder if it is applicable in a reliable delivery as well. If I understand it correctly, the data is only sent on request from the reader, hence, latency is introduced as the data has to be announced first. Wouldn't it be desired in some use-cases to send the data directly instead of announcing it first?
According to the OpenDDS Dev Guide, the push Mode is not included in the list of features which are not implemented, but stated in the DDSI-RTPS specification. However, I cannot find anything related to it or I am missing something.

**Comment by mitza-oci** [comment]
Adding heartbeats could certainly be done.  Is this something you're interested in contributing?

"Push mode" is part of a reference implementation in the spec, not part of the protocol requirements.  OpenDDS will "push" all changes.

**Comment by luigima** [comment]
> "Push mode" is part of a reference implementation in the spec, not part of the protocol requirements. OpenDDS will "push" all changes.

Let's consider the Messenger example project. A publisher writes data (10 samples) and a single subscriber receives it. 
Works flawlessly. However, my use case requires to capture the latency of each data transfer (at least in form of an approximation of the round trip time between sending the data and receiving the ACK).

Thus, we modify the implementation as follows: Instead of calling `wait_for_acknowledgments()` after sending all samples, we call it directly after each data write.
If you measure the time between writing the data, and receiving the ACK, you will notice that the value of the `heartbeat_period` configuration has a significant impact on the latency. In fact, the latency is most likely at least the `heartbeat_period` (default: 1sec).

This makes sense, as each data write is announced within a heartbeat first and then requested by the subscriber. In this sense, changes are pushed to the subscriber, that's true. 

In my case, however, it would be desired to trigger a heartbeat right away as soon as data is published. Instead, the data change will be announced with the next heartbeat which introduces a delay. 

Is there a possibility to optimize the process? Can I somehow trigger a heartbeat? Reducing the `heartbeat_period` to a minimal value is certainly not the best method.

**Comment by jrw972** [comment]
When a reliable writer writes a sample, OpenDDS sends it and saves it in a cache for reliable resend.
Some time later and periodically, OpenDDS will send a heartbeat announcing the sample.
The reader will then positively or negatively acknowledge the sample.  Assuming that the reader and writer have a common `heartbeat_period`, then nominally, the sample will be acked one `heartbeat_period` after it is written (.5 of the period on the writer and .5 of the period on the reader [naks are also sent periodically]).  Notice that this allows a writer to send a number of samples while only sending a single heartbeat and eliciting a single acknack.  Furthermore, the reader only "requests" missing data, i.e., in a favorable environment, most acknaks will only be positive acknowledgements.

This explains your observed connection between `wait_for_acknowledgements()` and `heartbeat_period`.

I believe what you want is for the reader to send an acknack for every data sample it receives.  This is prohibited by the specification in section 8.4.2.3.4.  The next best thing, as you have correctly concluded, would be to send a heartbeat for or with every data sample.  Obviously, this has performance implications so if it were added to the codebase, it would be configurable.

**Comment by mitza-oci** [comment]
> However, my use case requires to capture the latency of each data transfer (at least in form of an approximation of the round trip time between sending the data and receiving the ACK).

Could you describe this requirement in some more detail?  There are performance analysis tools available in the repository that could be useful for your scenario (see `performance-tests/bench_2`).

Since the RTPS protocol uses a cumulative acknowledgement model, looking for individual acknowledgements may not be the way to go.  Ideally applications rely on OpenDDS's publish/subscribe decoupling and distributed caches without introducing additional blocking via `wait_for_acknowledgements`.

**Comment by luigima** [comment]
> Furthermore, the reader only "requests" missing data, i.e., in a favorable environment, most acknaks will only be positive acknowledgements.
> [...] nominally, the sample will be acked one heartbeat_period after it is written [...] Notice that this allows a writer to send a number of samples while only sending a single heartbeat and eliciting a single acknack.

Now I got it. This is what I initially thought but got confused later on due to the observed behavior.

In order to clarify my situation here my use-case in very general terms:
I try to reconstruct the behavior of a distributed system which was designed and is tested/simulated with false assumptions. 
E.g. the latency/bandwidth/reliability/... of transferring data between nodes is unknown until we deploy the system on real hardware. 
In order to correct those false assumptions I want to capture the dataflow on real hardware which can be replayed in simulations afterwards.

In my case, approximations are sufficient. I do want to calculate the latency leveraging the round-trip time but I have to avoid as much overhead as possible, as the system behavior would be impacted otherwise. 
E.g. sending back the same message as the acknowledgment would cause significantly more overhead than simply wait for an ACKNACK which is sent by design anyway.

The distributed system I am working on is based on OpenDDS. Thus, I am currently searching for a method to capture the latency of each data transfer specifically in an OpenDDS environment, under the assumption that the system clocks cannot be synced easily. This is, however, what all approaches in /performance-tests assume.

My initial though was to use `wait_for_acknowledgements()` which seemed promising, as further overhead would be avoided.
On the downside, `wait_for_acknowledgements()` is only useful if we send data to a single subscriber (most of the time this is the case in my system though).
And, of course, the cummulated heartbeat method of sending ACKNACKs introduces delay compared to the TCP approach of exchanging ACKs.
 
Speaking of TCP, by using it as the transport protocol below RTPS I would probably be able to intercept the network traffic, independently from OpenDDS.

This also makes me wonder if DDS ACKNACKs and heartbeats still have to be sent when TCP already confirms the delivery. 
Most likely for fallback reasons when a connection is closed and has to be recovered?

However, a solution which includes UDP communication would be desired.

> The next best thing, as you have correctly concluded, would be to send a heartbeat for or with every data sample. Obviously, this has performance implications so if it were added to the codebase, it would be configurable.

Instead of configuring it as a parameter, triggering a heartbeat manually by calling a specific method might be more flexible though.
Alternatively, why not allow to piggy-backing it to the actual data message? Seems to be more intuitive to me and in certain scenarios this would reduce the network traffic if the data writer does not burst tons of messages.

**Comment by jrw972** [comment]
You can capture RTPS independently of OpenDDS.  Wireshark has dissectors for it.

There is an RTPS over TCP spec that is still a draft, I believe.
I assume that you know that OpenDDS has a TCP transport but this may or may not fit into your plans.

Theoretically, a heartbeat can be bundled with a data message.  Currently, OpenDDS does not do this but it may in the future.  However, the decisions as to when/if this happens has to be configurable for the reason you stated.

Are you trying to profile OpenDDS, the infrastructure (host + network), or both?  If you are profiling OpenDDS, then look at the performance tests.  If you are profiling the network, then there are tons of resources on that.  If you are attempting to use OpenDDS and/or RTPS as a tool to measure the performance of your infrastructure, you will have to find some work arounds because they were not designed nor instrumented to do so.

However, if you are interested purely in roundtrip latency, then I can tell you how I would hack OpenDDS to give me that information.  OpenDDS contains an implementation of [ICE](https://tools.ietf.org/html/rfc8445).  When enabled and configured correctly, each participant will periodically send STUN binding requests to other participants that it is has discovered.  If you add a custom time attribute to the binding request and return it in the response, then you can measure the round-trip latency.  If you add a custom payload attribute, you can start experimenting with payloads of different sizes.  Eventually, I want to do something like this to discover the path MTU between two hosts and report a latency statistic.

**Comment by luigima** [comment]
Thanks for the help. I will probably go with a TCP transport.
