### ISSUE TITLE
Messenger Example on Raspberry not working

### ISSUE THREAD

**Issue by Purdbull** [objectcomputing/OpenDDS#2318]
Hello,

I installed OpenDDS on a Raspberry 4 according to this Guide: https://opendds.org/quickstart/GettingStartedPi.html
When it comes to starting ./run_test.pl I get this Error:
```
/home/pi/OpenDDS/build/target/bin/DCPSInfoRepo -ORBDebugLevel 10 -ORBLogFile DCPSInfoRepo.log -o repo.ior
ERROR: Cannot Spawn: <home/pi/OpenDDS/build/target/bin/./DCPSInfoRepo> not found
ERROR: waiting for Info Repo IOR file
```

Im very greatful for any help!

**Comment by iguessthislldo** [comment]
How much did you copy over to the Pi?

**Comment by Purdbull** [comment]
> How much did you copy over to the Pi?

I have build the whole thing directly on the Pi 4, so everything should be there.

**Comment by Purdbull** [comment]
An other Error I get is that run_test.pl in the Messenger example cant locate PerlDDS:Run_Test module. I looked into the PerlDDS Directory and the Run_Test.pm file is there

**Comment by iguessthislldo** [comment]
> I have build the whole thing directly on the Pi 4, so everything should be there.

Okay, well the guide you linked is for cross-compiling on a PC and copying over to the Pi, so I was guessing you didn't copy everything over. Building it on the Pi will work as well, but it's going to basically be the same as [a normal Linux build](https://opendds.org/quickstart/GettingStartedLinux.html) instead of following the Raspberry Pi guide. If it's missing `DCPSInfoRepo`, then it sounds like the build isn't complete. What did you pass to configure?

**Comment by Purdbull** [comment]
./configure --target=linux-cross --target-compiler=/opt/cross-pi-gcc/bin/arm-linux-gnueabihf-g++

That was my configure- command. But the Pi is not missing the inforRepo, he cannot find the PerlDDS::Run_Test_Module. I think thats why he cannot "spawn" the info repo

**Comment by iguessthislldo** [comment]
Using `--target=linux-cross` is the opposite of building the whole thing directly on the Pi, so I'm not sure what you're build looks like. If you followed the Rapsberry Pi guide, but did it all on the Raspberry Pi with the cross compiler we provide it's not going to work because the cross compiler is for x86 Linux. This makes sense for the first error if it can't find InfoRepo because it didn't get built. The second error where it didn't find `PerlDDS` sounds like you need to `source setenv.sh` before running `run_test.pl`.

If you want to build on the Pi I would suggest deleting the existing OpenDDS on the Pi and starting over with the [Linux instructions](https://opendds.org/quickstart/GettingStartedLinux.html).

**Comment by tobi4321** [comment]
I also have tried to build OpenDDS on a Ubuntu system. After installation i used source setenv.sh. When i tried to run run_test.pl i got the following message:

Can't locate PerlDDS/Run_Test.pm in @INC (you may need to install the PerlDDS::Run_Test module) (@INC contains: /bin /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./run_test.pl line 15.
BEGIN failed--compilation aborted at ./run_test.pl line 15. 
-------------------------------------------------------------------------------------

So i looked into the run_test.pl at line 15 and tried to set: use lib "my path to dds/OpenDDS-3.16/bin";

After that i have tried to run_test.pl again... and got the next error:

 Can't locate PerlACE/Run_Test.pm in @INC (you may need to install the PerlACE::Run_Test module) (@INC contains: /home/buehlto1/OpenDDS-3.16/bin /bin /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/buehlto1/OpenDDS-3.16/bin/PerlDDS/Run_Test.pm line 5.
BEGIN failed--compilation aborted at /home/buehlto1/OpenDDS-3.16/bin/PerlDDS/Run_Test.pm line 5.
Compilation failed in require at ./run_test.pl line 14.
BEGIN failed--compilation aborted at ./run_test.pl line 14.
----------------------------------------------------------------------------------------------------------

I searched for that module and set the path to this module in run_test.pl: use lib "mp path to dds/OpenDDS-3.16/ACE_wrappers/bin";

the next try got me a new error:

fileparse(): need a valid pathname at /home/buehlto1/OpenDDS-3.16/ACE_wrappers/bin/PerlACE/TestTarget.pm line 122.

At this position i stopped searching for whats causing the errors because it seems to be a never ending story...

The first few lines of the run_test.pl now look like this:

eval '(exit $?0)' && eval 'exec perl -S $0 ${1+"$@"}'
    & eval 'exec perl -S $0 $argv:q'
    if 0;

# -*- perl -*-

use Env (DDS_ROOT);
use lib "$DDS_ROOT/bin";
use Env (ACE_ROOT);
use lib "$ACE_ROOT/bin";
use lib "/home/buehlto1/OpenDDS-3.16/ACE_wrappers/bin";
use Getopt::Long;
use lib "/home/buehlto1/OpenDDS-3.16/bin";
use PerlDDS::Run_Test;

use strict;

//here begins the code

------------------------------------------------------------

For me it seems like there is a problem with perl or anything like that. My Ubuntu version is 18.04 LTS.
I hope my description about our problem is detailed enough.

**Comment by iguessthislldo** [comment]
@tobi4321 You need to run `source setenv.sh` too.

**Comment by tobi4321** [comment]
i did...

**Comment by iguessthislldo** [comment]
Oh, sorry I missed that part. If you have to set these paths manually it sounds like something is wrong with the `setenv.sh` file. I think this issue is probably separate, so can you make a new issue for this and post the `setenv.sh` you have?
