### ISSUE TITLE
Cross-compile with Java for linux-cross in not supported.

### ISSUE THREAD

**Issue by stefanobianconi3** [objectcomputing/OpenDDS#2518]
Following the instructions to run OpenDDS on Raspberry Pi [https://opendds.org/quickstart/GettingStartedPi.html](url), I get the error passing **--java** at the end of the configure script.
The script:
`./configure --target=linux-cross --target-compiler=/opt/cross-pi-gcc/bin/arm-linux-gnueabihf-g++ --java`
 
The error:
`Cross-compile with Java for linux-cross in not supported.
Stopped at ./configure line 1201.`

Is it actually possible using OpenDDS on a Raspberry OS with Java?

Anyway I could try to build directly OpenDDS on a Raspberry in order to use all the development environment, but which is the C++ compiler to use for the building?

**Comment by iguessthislldo** [comment]
I wrote that error and I think this was an oversight on my part. If you add this line:

```perl
             'java_platform' => 'linux',
```

after [this line in the configure script](https://github.com/objectcomputing/OpenDDS/blob/c5934157b2b29c843514acdd2d57e3c348916821/configure#L78), then I think it should let the cross-compile build go ahead. I don't know if I got the indent right, but in Perl that doesn't matter.

It was supposed to be a safety check because before it would use always use the host Java platform, which would be wrong for Windows to Android cross compiles, but it needs to do that for Linux to Linux cross compiles.

Will post a PR for this.

**Comment by iguessthislldo** [comment]
> Anyway I could try to build directly OpenDDS on a Raspberry in order to use all the development environment, but which is the C++ compiler to use for the building?

If you did want to build directly on the Pi, then the letting it default to the system compiler would be fine: `./configure --java`

**Comment by stefanobianconi3** [comment]
I changed the configure script and it goes ahed. Then I compiled using 'make' but at the end $DDS_ROOT/lib folder is empty. I expected it to have the jars library and include them on the classpath of the java application on raspberry. Is that normal?

**Comment by iguessthislldo** [comment]
Cross compiled builds go to `build/target`, so you should find the jar and so files in `build/target/lib`.
