### ISSUE TITLE
Time-Based Filter QoS

### ISSUE THREAD

**Issue by mitza-oci** [objectcomputing/OpenDDS#268]
The spec requires a Time-Based Filter reader to eventually see the latest sample per instance. In cases where that latest sample would normally be suppressed by the TBFilter, the current implementation does not eventually deliver that later sample. This isn't an issue for periodic writers.

In terms of implementation, consider reusing much of the code for reader-side Deadline (timer support, etc.) to make the most recent sample available if the writer stops updating the instance.

_This issue was originally on the SourceForge tracker, which we are no longer using._

**Comment by brianjohnson5972** [comment]
I think this is the important part of the spec:

"In the case where the reliability QoS kind is RELIABLE then in steady-state, defined as the situation where the DataWriter does not write new samples for a period “long” compared to the minimum_separation, the system should guarantee delivery the last sample to the DataReader."

So we only need to guarantee that the sample is re-sent if the DataReader has a reliability QOS kind of RELIABLE.

Also, the following:

" The HISTORY and RELIABILITY QoS affect the behavior of the middleware with respect to the samples that have been determined to be of interest to the DataReader, that is, they apply after the TIME_BASED_FILTER has been applied. "

indicates that filtering should prevent samples from being added to the history (which we already do), but seems to be ambiguous as to whether the Reliably delivered sample should be applied to the History QOS. But I think that is the way it has to work, since we are reporting a sample and a subsequent request to get the last sample should return that sample.

**Comment by mitza-oci** [comment]
The phrase "sample is re-sent" seems to imply that there's an actual network transaction here.  That might not be the case.  It's an implementation detail whether or not the writer actually sends a sample.  The reader could just cache it.

**Comment by brianjohnson5972** [comment]
Poor word choice, edited original comment

**Comment by brianjohnson5972** [comment]
New Test scenario for Time Based Filter with Reliability type of Reliable
![timebasedfilter](https://cloud.githubusercontent.com/assets/10270043/19978696/cc189d38-a1c5-11e6-98e0-7018a60f773f.JPG)

**Comment by brianjohnson5972** [comment]
Not really part of this problem, but in the affected code:
In set_instance_state, store_instance_data is being called and the filtered flag is ignored and notify_read_conditions() is called even if there was no sample added to the history(filtered).  It isn't producing a wrong state, since those listening for the read condition should see that they already saw the last instance sample in history, but this will cause spurious read conditions.  Will clean this up with the change to avoid signalling there is new data when there is none.

**Comment by brianjohnson5972** [comment]
Committed (c0beb8e2c7621047972e7714b36bf02908035175, ba5fd1074b5599797a1030accfb58f39e7c9248e, 77931ad48c79e93e8dc51317be28d31b17571b88)

**Comment by mitza-oci** [comment]
Fixed by pull request #377.  This issue will remain open until test results have been verified (and possibly, test cases are extended).

**Comment by mitza-oci** [comment]
Fixed and test is passing
