### ISSUE TITLE
Setting of CIAO_ROOT/DANCE_ROOT to unused causes invalid include paths when invoking tao_idl

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#2781]
The setting of CIAO_ROOT/DANCE_ROOT to `unused` at https://github.com/objectcomputing/OpenDDS/blob/045cde5cb9e4a01d8291917ba4a1527feb071e88/configure#L2163 causes tao_idl/opendds_idl to add some invalid paths to the include of the preprocessor. On ACE/TAO github master we already don't use CIAO_ROOT/DANCE_ROOT in MPC.cfg, so there the warnings about them being unused when running MPC doesn't show anymore. 

```
tao_idl: spawning: clang++ -D__TAO_IDL=0x070002 -I. -I/home/johnny/ACE/OpenDDS/ACE_TAO/TAO -I/home/johnny/ACE/OpenDDS/ACE_TAO/TAO/tao -E -I/home/johnny/ACE/OpenDDS/ACE_TAO/TAO/orbsvcs -Iunused -Iunused/ciao -Iunused/ccm /tmp/tao-idli_teXimJ.cpp

opendds_idl: spawning: clang++ -D__TAO_IDL=0x070002 -I. -I/home/johnny/ACE/OpenDDS/ACE_TAO/TAO -I/home/johnny/ACE/OpenDDS/ACE_TAO/TAO/tao -E -I/home/johnny/ACE/OpenDDS/ACE_TAO/TAO/orbsvcs -Iunused -Iunused/ciao -Iunused/ccm -D__OPENDDS_IDL=0x031800 -D__OPENDDS_IDL_HAS_FIXED -I/home/johnny/ACE/OpenDDS -D__OPENDDS_IDL_HAS_ANNOTATIONS /tmp/tao-idli_5EiiqT.cpp
```

**Comment by mitza-oci** [comment]
This is essentially "by design" but could be adapted based on the ACE version.
When the code was written, it was intended to generate `-I/unused` et. al. which would never be successfully used by the preprocessor to locate a header file.
The alternative was `-I/ciao` which may actually resolve to something (that we don't want it to).  We saw this happen when first setting up the `configure` script.

**Comment by mitza-oci** [comment]
I'm not sure what would be changed here.  There's no downside of adding extra `-I` paths that don't get used.
