### ISSUE TITLE
Configure script doesn't make use of parallel MPC workers

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#315]
The OpenDDS configure script invokes MPC but doesn't make use of the parallel MPC workers, could save time with each configure

**Comment by mitza-oci** [comment]
There's some more complexity involved in this: how many workers?  do we attempt to clean up the temp dir if things go wrong?  The workspace is small enough that the basic mwc.pl should take 30-45 sec or less on typical hardware (whatever that is?)

I wouldn't be opposed to adding it, but the user can also specify --mpcopt to customize configure.

**Comment by jwillemsen** [comment]
Would take as many workers as there are cpu cores on the system

**Comment by jwillemsen** [comment]
Personally I would also just generate the workspace for the core the user needs, not all examples and tests, that is only necessary when someone wants to compile just one

**Comment by mitza-oci** [comment]
Taking as many workers as CPU cores assumes there is no other work on the system -- seems like an odd assumption to me.  The user adds more CPU cores in order to do more things at the same time (for example, many Jenkins executors), and the result is that the system is oversubscribed.

Generating just the core is what "--no-tests" does.  We could make that the default but we would need some other changes first.  Since DevGuideExamples is still included with --no-tests, I'd like to clean those up and give the user enough to get started and run a basic "smoke test" with RTPS.
