### ISSUE TITLE
If ACE_USES_WCHAR is set to 1, Parser.cpp compilation fails.

### ISSUE THREAD

**Issue by bluenlive** [objectcomputing/OpenDDS#3226]
When ACE_USES_WCHAR is set to 1 in the Visual Studio, compilation of `dds\FACE\config\Parser.cpp` fails.
This phenomenon occurs in the functions `parse()`, `parse_topic()`, `parse_connection()`, `parse_qos()`, `parse_sections()`.

Look at the function `parse()`.
The function `parse()` is declared `int parse (const char*filename)`.
And, `filename` is passed as `import.import_config(filename)`.

The function `import_config()` is declared `import_config(const ACE_TCHAR*filename)`, and when ACE_USES_WCHAR is 1, ACE_TCHAR is declared `wchar_t`, not char.

Other functions have similar problems.

I'm asking because I want to check, but in these cases, is it the right way to use `ACE_TEXT_CHAR_TO_TCHAR()` or `ACE_TEXT_ALWAYS_CHAR()`?
Or should we find another solution?

**Comment by iguessthislldo** [comment]
Yes, if the ACE interface only supports `const ACE_TCHAR*` like `import_config`, then `ACE_TEXT_CHAR_TO_TCHAR` has to be used if the string is in a `const char*`.

Thanks for finding this, it'd be great if you could open a PR with this fix if it works. It sounds like we don't have a build where FACE and `ACE_USES_WCHAR` are both used at the same time though, so I don't know how many of these kinds of problems you're going to find.

**Comment by mitza-oci** [comment]
Set the MPC feature `uses_wchar=1` to configure ACE with `ACE_USES_WCHAR`. See `$ACE_ROOT/bin/MakeProjectCreator/config/ace_unicode.mpb` for how this works in ACE.
If you're using the OpenDDS configure script, pass `--features=uses_wchar=1`

**Comment by iguessthislldo** [comment]
@bluenlive To address your "confused" emoji and expand on what Adam said:

> When ACE_USES_WCHAR is set to 1

I didn't pick up on this originally, but I think Adam is saying this because the way you phrased makes it sound like `ACE_USES_WCHAR` is manually being set to 1 when the proper way to do it is through the `uses_wchar` MPC feature.

Looking at the mpc file for FACE, this appears to be the case because `Parser.cpp` wouldn't build if `uses_wchar` was being used:

https://github.com/objectcomputing/OpenDDS/blob/143859dac28b68f27549abb9252f53307a65c0f5/dds/FACE/OpenDDS_FACE.mpc#L3

So this line would also have to be removed for this to work properly.

**Comment by bluenlive** [comment]
> 

I understood that instead of manually setting ACE_USE_WCHAR, setting it using --features=use_wchar=1 was the right way, and I only put on emoticons because I had nothing to add.
(It means that I understood the answer well)

I was going to put on the "smile" emoticon, but I accidentally put on the "ambiguous" emoticon.
I'm sorry for bothering you.

Thank you for your kind explanation.
