### ISSUE TITLE
iShapes example use C++11 instead of boost?

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#326]
The current iShapes example requires boost to compile and use. Instead of depending on boost it would to my idea be easier to depend on C++11 and remove the boost dependency completely.

**Comment by jwillemsen** [comment]
Related to issue #325.

**Comment by mitza-oci** [comment]
A starting point would be to have a preprocessor-based switch between boost and C++11.  It's a very small amount of code that has any boost dependency.

**Comment by jwillemsen** [comment]
Adding a preprocessor check would be possible, we can use ACE_HAS_CPP11 for that. Will try to do that somewhere the coming week, feel free to assign this one to me

**Comment by mitza-oci** [comment]
When I looked through for #includes of boost, mostly it's shared_ptr.  There are a few others:

- DDSShapeDynamics.cpp uses cstdint from boost but it really should just be types from the CORBA namespace since it's interacting with IDL sequences
- ShapesDialog.cpp has lexical_cast from boost, in C++11 it can use std::to_string

**Comment by jwillemsen** [comment]
See pr #329

**Comment by jwillemsen** [comment]
Fixed
