### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by MDreamChaser** [objectcomputing/OpenDDS#3387]
I am trying to run the Java example   Intellij IDEA using Ubuntu. 

I set  VM arguments and JVM arguments have specified "-Djava.library.path=${DDS_ROOT}/lib"
When I run System.getPriperties("java.library.path"), I receive ${DDS_ROOT}/lib
I get no compiler errors. But when I run the code and try to create a new DomainParticipantFactory I receive a runtime error:

![1646655384(1)](https://user-images.githubusercontent.com/43842714/157032840-b3a0e10a-3c46-4f56-abf0-1ea90b28757a.png)

**Comment by mitza-oci** [comment]
The character used to separate path elements on Linux is `:`, not `;`.

Can you run tests from the shell directly (without IDEA)?

**Comment by MDreamChaser** [comment]
Thanks for your reply.
It is ok, I added $DDS_ROOT/lib to the file /etc/profile and ran source /etc/profile.
Then, I checked with command java XshowSettings java.library.path, it worked well. The system must be rebooted, if not, IEDA will return errors.

**Comment by mitza-oci** [comment]
I don't recommend changing system-wide settings but that's your call.  In general, if you need to have root in order to do routine development work then something has gone wrong.  Linux has a number of mechanisms to influence shared library loading including the LD_LIBRARY_PATH environment variable and RPATH and related headers in the library itself.
