### ISSUE TITLE
Reconnection of publisher with the subscriber only works with BEST_EFFORT_RELIABILITY_QOS

### ISSUE THREAD

**Issue by dvucko** [objectcomputing/OpenDDS#3453]
Consider the following scenario with `rtps_udp` transport.

1. Publisher is normally writing data and subscriber is normally reading it.
2. Subscriber process is killed. Publisher is now, obviously, getting timeouts when waiting for acknowledgments after writing data.
3. Subscriber comes back online. Publisher should now continue writing data successfully.

When using `BEST_EFFORT_RELIABILITY_QOS`, the subscriber automatically starts receiving messages again after coming back online. However, when using `RELIABLE_RELIABILITY_QOS`, the publisher will continue experiencing timeouts, and no new message can be published anymore. I tried to re-establish a connection using WaitSet with the same conditions and logic that was used (successfully) initially, but to no avail.

Is there any built-in functionality that would automatically re-establish the connection in this scenario? Or is this perhaps by design?

**Comment by jrw972** [comment]
Since you mentioned that the publisher is waiting for acknowledgements, I'm going to assume that the publisher writes a sample and then waits for acknowledgement.

There are two scenarios to consider with respect to the subscriber being killed.
First, if it is a clean shutdown, then the subscriber and the publisher will dis-associate.
In this scenario, waiting for acknowledgement won't do anything because there are no subscribers.
Second, if it is not a clean shutdown, then the publisher will be associated with the new subscriber and the old subscriber.
Since the old subscriber is obviously not sending acknacks, then waiting for acknowledgement will block as expected.
Only when the old subscriber times out should the system return to normal operation.

In general, waiting for acknowledgements leads to counter-intuitive results like this and there are gaps in OpenDDS's implementation of it.

**Comment by dvucko** [comment]
Thank you, Justin.

Your assumption about waiting for acks is correct. I had the non-clean shutdown in mind. So essentially the restarted subscriber should be considered a completely new one, and I guess re-initialized completely. If I remove `wait_for_acknowledgments()` after issuing a `write()`, the problem disappears in the sense that the subscriber, after having re-started, will be reading data normally again. The obvious downside is that this effectively makes the behavior equivalent to the best effort QOS, with no timeouts being triggered in case of a subscriber no longer being alive.

**Comment by jrw972** [comment]
I think it's a question of scope.  Reliability means that a reliable publisher will reliably communicate samples to all reliable subscribers.  It was not designed to answer the problem of ensuring that every sample makes it to _at least one_ subscriber.  For that, you would need to look elsewhere like durability or providing a feedback topic that allows the subscriber to manually acknowledge receipt so the publisher can progress.
