### ISSUE TITLE
Can't interoperate with CycloneDDS due to enum extensibility encoding

### ISSUE THREAD

**Issue by smnrgrs** [objectcomputing/OpenDDS#3676]
I have an IDL containing an enum. If comment it out I can pub/sub between OpenDDS (3.20) and CycloneDDS. If I uncomment my enum I get `(300870|300890) Sedp::match_continue - WARNING Data types of topic SERVICEINFO does not match (inconsistent)` and no reader/writer match.

I've been discussing this issue on the CycloneDDS [project page](https://github.com/eclipse-cyclonedds/cyclonedds/issues/1345#issuecomment-1210693175). 

The view from CycloneDDS is that the issue relates to OpenDDS not encoding the extensibility for the enum.

> When checking the compatibility of the types of a reader and writer, one of the rules is that the extensibility must match, but for enums there is a problem in the spec:
> 
> it states that enums can be @final or @appendable (section 7.4.1, table 12)
> it states that the extensibility must match for the types to be compatible (section 7.2.4.4.7, table 18)
> a comment in the IDL definition of the TypeObject (appendix B) says that the TypeFlag (a.k.a. EnumTypeFlag a.k.a. enum_flags field) is unused in the header, but this is where the extensibility would be encoded.
> We decided to solve this problem by ignoring the "unused" comment in the IDL and encode the extensibility in there so that we can satisfy the first two points. OpenDDS does not, and therefore the Cyclone and the OpenDDS variants are incompatible because of the second point.
> 
> We're pretty sure this is a bug in OpenDDS ([they seem to have their doubts as well](https://github.com/objectcomputing/OpenDDS/blob/75b9a44ee52260b9100254d8768a77c2a3861a36/dds/DCPS/XTypes/TypeAssignability.cpp#L1072)) and they have filed an issue with the OMG requesting clarification. The processes at the OMG are just unbearably slow.
> 
> We think the best solution is for OpenDDS to also start encoding the extensibility the obvious way.
>

**Comment by mitza-oci** [comment]
Looking into this... I think I disagree with the "We think the best solution is..." part that you quoted, but we should be able to find a way to resolve it.  It may need a configuration option to allow backwards compatibility.

In Cyclone is an enum with unspecified extensibility treated as final, appendable, or rejected?

**Comment by sonndinh** [comment]
I believe OpenDDS does encode enum extensibility, i.e., the `enum_flags` field in enum TypeObject. Things like the TypeConsistencyEnforcementQosPolicy in data reader can also affect the type matching result.

**Comment by mitza-oci** [comment]
It's not set in `typeobject_generator::generate_enum_type_identifier`

**Comment by thijsmie** [comment]
Hi there, CycloneDDS committer here. This inconsistency between CycloneDDS and OpenDDS also unearthed a mistake in CycloneDDS for which the fix was just merged. Not specifying the extensibility of an enum in the typeobject used to result in a silent failure, but now will result in a rejection. OpenDDS will also reject the CycloneDDS enum typeobject with IS_FINAL set (which is our default when the user does not annotate the extensibility in IDL).

We considered adding a compatibility mode for OpenDDS but decided against it, because it still would not work unless OpenDDS also added a compatibility mode for the Cyclone side, and judging from the OMG issue mentioned you actually agree with us on what the correct interpretation of the spec is is in this case 😁

**Comment by mitza-oci** [comment]
Thanks for the additional info.  The spec issue is there to point out the problem and improve the spec for a future 1.4 version.  It doesn't have a proposed resolution yet.

Since the 1.3 spec is clear that these flags are `// Unused.`, instead of a compatibility mode "for OpenDDS" I'd consider accepting such a TypeObject without differentiating based on which implementation generated that TypeObject.  But of course this is up to you.

**Comment by smnrgrs** [comment]
> Looking into this... I think I disagree with the "We think the best solution is..." part that you quoted, but we should be able to find a way to resolve it. It may need a configuration option to allow backwards compatibility.
> 
> In Cyclone is an enum with unspecified extensibility treated as final, appendable, or rejected?

It gets rejected

**Comment by mitza-oci** [comment]
We can change OpenDDS to have enums that are explicitly annotated with extensibility use the enum_flags in TypeObject to encode the same.  Would that work for your use case, @smnrgrs?

**Comment by smnrgrs** [comment]
I believe it would, thank you.

**Comment by jrw972** [comment]
https://github.com/objectcomputing/OpenDDS/pull/3686

**Comment by smnrgrs** [comment]
Will do, thanks for your efforts.

**Comment by smnrgrs** [comment]
I can confirm that this issue seems to be resolved. 

Summary of test config:
OpenDDS Master 36c5829
CycloneDDS V0.11.0 e54f6eeaa

OpenDDS requires 'OPENDDS_IDL_OPTIONS -Gxtypes-complete' in idl compile step
I have specified @final for topcs, enums and structs in the IDL.

**Comment by mitza-oci** [comment]
@smnrgrs thanks for the confirmation
