### ISSUE TITLE
Matlab/Simulink support

### ISSUE THREAD

**Issue by guilhermecgs** [objectcomputing/OpenDDS#379]
Are you planning any support fo Matlab/Simulink in future releases?

Maybe a simulink blockset for reading and writing data between models?

**Comment by mitza-oci** [comment]
Nothing planned as far as I know.  I'm not familiar enough with these products to know what this would involve.  What would the tradeoffs be between having it in the OpenDDS repository vs. having it as an external add-on?

**Comment by guilhermecgs** [comment]
What I was thinking is something like this:

https://www.mathworks.com/videos/simulink-and-the-dds-support-package-107761.html

https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/hardware-support/files/dds-blockset-support-package-user-guide.pdf

It would be an external add-on to simulink, but this time free....

**Comment by mitza-oci** [comment]
I think that would be an excellent addition.  If anyone is willing to contribute it or sponsor development please let us know.

**Comment by guilhermecgs** [comment]
I agree it would be an excellent addition...

It would be possible to communicate 2 simulink models running in different machines

**Comment by mitza-oci** [comment]
Do you have a high-level overview of what would be required?  Is this something you can work on in the near term?

**Comment by guilhermecgs** [comment]
I am not an expert of dds but I do have some experience with Matlab/Simulink.  I think the list of high level requirements of this feature are:

* To develop a set of blocks in simulink (C++ SFunctions) to enable models sending and receiving data using OpenDDS
* Be able to transmit data to/from compiled models and interpleted models (and vice-versa);
* Suport c++ code generation from simulink models with native simulink targets
* Support co-simulation with third party softwares that also have DDS interface

If implemented, it **could** replace several Matlab/Simulink toolboxes that are quite expensive and do much less... ex:  

- https://www.mathworks.com/products/parallel-computing.html
- https://www.mathworks.com/products/distriben.html
- https://www.mathworks.com/hardware-support/rti-dds.html

However, answering your question, I unfortunately do not have the "man hours" to implement it myself.
Also, it is the police of the company I work for to implement it in a private repository, if it is the case to implement it.

**Comment by swatza** [comment]
This is something I have considered doing in the near future but don't know when I would get around to it.

**Comment by mitza-oci** [comment]
Some progress on Matlab integration:
https://sourceforge.net/p/opendds/mailman/opendds-main/thread/97df1670c0f37332b8ee98e7c0d6bf43%40jegaden.eu/#msg35917266

**Comment by guilhermecgs** [comment]
great! looking forward!

**Comment by jefix** [comment]
Hello,
 I've have been successful in exchanging data using OpenDDS in matlab, using the mex functions. 
It works as well with S functions bloks in simulink.
I'm running out of time right now, but very very  briefly here is how to get it working (I'll take some time to give a full exemple after my holildays )

1- create a mex function used to initiliase the ACE stuff ( this is quite a black box for me, I don't know what it really does ) : 
```

#include <matrix.h>
#include <mex.h>  
#include <ace/Init_ACE.h>        

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
     int aceinit= ACE::init();
     //initialize OpenDDS stuff
     if(aceinit==-1)
       mexErrMsgTxt("Cannot init ACE\n");
     else if(aceinit==0)
        mexPrintf("Init ACE OK\n");
     else if(aceinit>0)
        mexPrintf("Init ACE already called");

}
```
2 compile it  with command:

mex -g -output ../bin/mat64/aceinit -DWIN32  ../src/mat_aceinit.cpp  -I$(ACE_ROOT) -L$(ACE_ROOT)\lib -lACEd.lib 


3 to get your application mex function working with opendds, you'll need to declare  DDS::DomainParticipantFactory_vardpf, and DDS::DomainParticipant_var participant  outside of the mex function implementation. Declare them as static. 
Then be sure that at the first call of the mex function you do all the initialisation steps, like creating the particpant, topics, etc.. (use a if statement to check if its a first call for exemple.) On the second call of the mex function, you should be able to retreive data.
Just make sure you remove the statements from the Mex function:
```
    if (!CORBA::is_nil (participant.in ())) {
        participant->delete_contained_entities();
      }
      if (!CORBA::is_nil (dpf.in ())) {
        dpf->delete_participant(participant.in ());
      }
      ACE_OS::sleep(2);

      TheServiceParticipant->shutdown();
```

You have to release the participant using the mexAtExit function of matlab.
Insert the  `mexAtExit(CloseDDS)` during your first intialisation step of the mex function.
this function, CloseDDS, will be called by matlab when the mex functions is cleared ( clear functions in matlab) or if you quit matlab.

```
static void CloseDDS(void)
{
  mexPrintf("Free DDS memory allocations.\n");
  participant->delete_contained_entities();
  dpf->delete_participant(participant.in ());
}
```
`      TheServiceParticipant->shutdown();` should be removed from it.

compile your mex function: 
mex -g -output ../bin/youbinfile -DWIN32 -v COMPFLAGS='$COMPFLAGS /bigobj' allYourCFilesHere.cpp  -IallYourHeaderFiles -I$(ACE_ROOT) -I$(TAO_ROOT) -I$DDS_ROOT) -L$(ACE_ROOT)\lib -L$(ACE_ROOT)\..\lib\ -lACEd.lib -lTAOd.lib -lOpenDDS_Dcpsd.lib -lYOURIDLMESSAGE.lib 

option COMPFLAGS='$COMPFLAGS /bigobj' is because I had a lot of data structure described in my IDL file.

I'am using RTPS UDP transport.

Be sure to launch first the mex file that init ACE ( first point ) then launch your application mex file.
To restart, type clear functions. this will clear the participant.

if you want to release totally ACE, write the same mex function as ACE::init() but with ACE::fini().

I know it is a very short brief, sorry for that I'm runnning out of time! 
I'll come back on it.
Anyway, hope this help you to try it!
