### ISSUE TITLE
configure error in OpenDDS 3.22

### ISSUE THREAD

**Issue by MarcoRoccagliSigma** [objectcomputing/OpenDDS#3901]
Hi again,
i'm trying to build opendds version 3.22 for windows.
After opening the visual studio developer command as admin, i just type the configure.cmd to start the configuration process.
Anyway when the ACE+TAO dependencies are downloaded and extracted i have the following error:

**_Use of uninitialized value $prop_value in scalar chomp at configure line 473.
Couldn't get submodule.tools/rapidjson.openddsConfigureCommit from .gitmodules
Stopped at configure line 475.
ERROR: configure failed with errorcode 1_**

This does not happen in OpenDDS 3.21.
With this version i'm able to configure and compile successfully,

Any clue for this?
Thanks

**Comment by mitza-oci** [comment]
I think this was fixed after the 3.22 release.  See #3812 
One potential workaround is to copy the latest configure script from master.

**Comment by iguessthislldo** [comment]
There were actually two issues, but I'm not sure which issue this is, because I think they both have the same error message. One was that the configure script on Windows thought it could use git when it actually couldn't. That's what was fixed in #3812. Copying the configure script should fix that. The other issue was that if you did have git the 3.22 zip archives were missing the `.gitmodules` file so that file would have to be copied as well. This was fixed in #3580.

Now that 3.23 is out both of these issues have been fixed and 3.21 should be able to fixed manually by copying the updated versions of `configure` and `.gitmodules`, so I think we can close this issue.
