### ISSUE TITLE
DataWriterImpl::wait_for_acknowledgments() issue during shutdown TCP transport

### ISSUE THREAD

**Issue by huangminghuang** [objectcomputing/OpenDDS#433]

**Comment by mitza-oci** [comment]
wait_for_acknowledgements() was updated recently to work with RTPS.  The implementation for the tcp transport also changed, however there is an issue with it only during shutdown.  The writer side will believe that the reader has "acked" as long as the socket write goes through without errors (due to TCP's own reliability guarantees).  However, if the writer side shuts down immediately after wait_for_acks, the reader side may not have actually received and processed the data -- this is especially seen on the loopback adapter on Windows which shortcuts the network stack.

**Comment by mitza-oci** [comment]
@huangminghuang is this done now that PR #472 is in?
