### ISSUE TITLE
Calling set_expression_parameters on a cft with an invalid set of parameters doesn't return RETCODE_ERROR

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#491]
Using set_expression_parameters with an invalid set of parameters doesn't return RETCODE_ERROR. Found using our higher level dds4ccm unit tests.

**Comment by mitza-oci** [comment]
What is it about the parameters that makes them invalid?  Is there a test you can add to OpenDDS for this?

**Comment by jwillemsen** [comment]
Will analyze this further and will extend one of the OpenDDS tests for this

**Comment by jwillemsen** [comment]
We set this as CFT: ( (iteration &lt; %0) OR (iteration &gt; %1) ) OR (key = 'KEY_6')

But when setting the filter parameters we pass a string sequence of length 1

And using the following topic type

```
module DDS_Native
{
#pragma DCPS_DATA_TYPE "DDS_Native::CommonTestMessage"
#pragma DCPS_DATA_KEY "DDS_Native::CommonTestMessage key"
  /// @copydoc common.idl::CommonTestMessage
  struct CommonTestMessage {
    /// @copydoc common.idl::CommonTestMessage::key
    string key;
    /// @copydoc common.idl::CommonTestMessage::iteration
    long iteration;
  };

}; // module DDS_Native

```

**Comment by mitza-oci** [comment]
I don't see any requirement to check this eagerly.  Seems to be up to the implementation to decide how to do it.  There are use cases with short-circuiting boolean operators where you may know that you don't need all parameters.  But I wouldn't be opposed to checking eagerly if someone wants to contribute code for it.

**Comment by jwillemsen** [comment]
Section 2.2.2.3.3 of the DDS specification does say the following which does indicate to me that there should be some check

The expression_parameters attribute is a sequence of strings that give values to the ‘parameters’ (i.e., "%n" tokens) in the filter_expression. The number of supplied parameters must fit with the requested values in the filter_expression (i.e., the number of %n tokens).

**Comment by mitza-oci** [comment]
"fit with" is not a very precise phrase here.  I didn't see this part because I was looking at the places where the parameter list is given as an input (create_contentfilteredtopic and set_expression_parameters).

As I was saying, I won't have a problem with merging a pull request that adds this check.

**Comment by jwillemsen** [comment]
Any suggestion where to start to look to add this check?

**Comment by mitza-oci** [comment]
FilterEvaluator::walkOperand will be called on each operand, some subset of them are of type ParamVal.  Instead of just "return new Parameter...", determine from the Parameter object which number it is (add an accessor) and in the FilterEvaluator class, keep track of the maximum-valued one.  This maximum value can then be returned from a new method of FilterEvaluator.  This can be used by ContentFilteredTopicImpl to check that the number of parameters is correct.

**Comment by jwillemsen** [comment]
Thanks, will try to add this tomorrow

**Comment by jwillemsen** [comment]
Implemented the check, please review, these changes make several of our DDS4CCM AXCIOMA unit tests to run. Looks strange things happen when you first set an invalid parameter sequence and after that set a correct one but haven't analyzed that further because setting an invalid sequence now returns an error

**Comment by mitza-oci** [comment]
PR #492
