### ISSUE TITLE
Huge amount of valgrind reported leaks when running the OpenDDS unit tests

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#557]
Looks a lot of unit tests report leaks when they are ran with valgrind, could be that improvements are needed in the tests but it could be that there are leaks in the core itself. Setup a new valgrind enabled opendds build, should report new results soon at http://buildlogs.remedy.nl/fc_opendds_valgrind/index.html

**Comment by mitza-oci** [comment]
We are using GCC asan (address sanitizer) to do this kind of runtime analysis.  There is a build on the scoreboard.  If there are leaks in the core code reported by valgrind and not by asan, that would be important to fix.  It's also good to fix leaks due to test code.  Let's open an issue when there are specific stack traces to look at.

**Comment by jwillemsen** [comment]
Due to the huge amount of reported leaks it is very hard to see which are coming from the core code. The build is still running, this is definitive an area for improvement

**Comment by jwillemsen** [comment]
First valgrind build/test results are available now

**Comment by jwillemsen** [comment]
Created some separate issues, we do have a lot of leaks because the DDS entities aren't deleted
