### ISSUE TITLE
NOT_ALIVE_DISPOSED_INSTANCE_STATE and get_key_value

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#627]
During some testing I noticed that when we get a NOT_ALIVE_DISPOSED_INSTANCE_STATE in a listener calling after that get_key_value with the passed instance handle doesn't give the keys but a RETCODE_BAD_PARAMETER, need to extend an unit test for this and see why this doesn't work

**Comment by mitza-oci** [comment]
I assume this is on the DataReader?  I haven't had time to check the code but I would guess that it's no longer storing the required data on that instance.  Does the listener call a read() or take() before get_key_value()?

**Comment by jwillemsen** [comment]
Yes, did see it in my FooTest3_0 extensions for the query condition, we do a take_w_condition there.

**Comment by mitza-oci** [comment]
The instance data needed for `get_key_value` is removed as part of the `take` operation, specifically in the "Take" step of `RakeResults<SampleSeq>::copy_into`.

The key is available in the data sample (even though it's !valid_data).  I'm not sure that was the case when this Issue was first written.

In section 2.2.3.22 READER_DATA_LIFECYCLE:
> Under normal circumstances the DataReader can only reclaim all resources for instances for which there are no writers and for which all samples have been ‘taken.’

A consequence of "reclaim all resources" is that `get_key_value` no longer works.

**Comment by mitza-oci** [comment]
To run this test, change to `tests/DCPS/FooTest3_0` and run the test script with the argument `dispose_qc`.  The subscriber process will run `DataReaderQCListenerImpl::on_data_available` and reach the case where the instance state is `NOT_ALIVE_DISPOSED_INSTANCE_STATE`.
