### ISSUE TITLE
service/domain participant::create_typeless_topic

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#674]
The sp/dp have a `create_typeless_topic` operation which is not part of the DDS spec and only used in the `tests/DCPS/RecorderReplayer/Relay.cpp` test. Can't we solve that test in a different way, that way we could remove this operation from the core and maybe that is enough to remove the `has_dcps_key` of the type specific typesupport

**Comment by mitza-oci** [comment]
It is part of the public API for use with Recorder/Replayer.  If you would like to propose another way of handling it, go ahead.  has_dcps_key is needed for RTPS Discovery because the GUIDs are different for keyed vs. unkeyed (which is probably a bug in the spec but oh well).  See EndpointManager::assign_publication_key().

**Comment by jwillemsen** [comment]
Ok, maybe we can solve  has_dcps_key in another way so that it doesn't need to be in the type support IDL, more something internal

**Comment by mitza-oci** [comment]
It is already internal since it's OpenDDS::DCPS::TypeSupport, not DDS::TypeSupport.

**Comment by jwillemsen** [comment]
It is part of the generated type specific type support implementation which is used by the DDS user, I agree it is part of an OpenDDS specific extension

**Comment by mitza-oci** [comment]
I'm not sure what problem you're trying to solve here.  One additional virtual method in a class that already has a vtable is not significant overhead.

**Comment by jwillemsen** [comment]
Except the `unregister_type` all other operations from `OpenDDS::DCPS::TypeSupport` look to be for the OpenDDS core, not for the DDS user. Would like to hide those from the user by moving them somewhere else, this is also of interest for us for AXCIOMA where we want to get as less possible exposure of OpenDDS internals because some of them give challenges when combining IDL to C++ and IDL to C++11 in one source file.

**Comment by mitza-oci** [comment]
Everything related to TypeSupport meets the requirements of the spec.  It would be nice to have a clean separation between implementation and interface (just like with DataWriterImpl, etc.), but the spec doesn't work that way since the user has to construct the object directly, see 2.3.2 "classes that do not have factory operations."  If you want to propose a different way of handling this (that's backwards-compatible), then please do that in a separate issue/PR since it's not really related to the discussion above.
