### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by huynam** [objectcomputing/OpenDDS#765]
Does OpenDDS support ssl? If yes, how do I configure it?

**Comment by mitza-oci** [comment]
There is no SSL support in OpenDDS.  Because the way OpenDDS uses sockets is quite different from something like HTTP, a VPN is the preferred secure encapsulation method for DDS traffic.

There is a new DDS Security specification from the OMG which will provide a fine-grained security model for DDS entities.  Please contact us if you're willing to sponsor this effort.  https://objectcomputing.com/products/opendds/
