### ISSUE TITLE
IDL for dynamic data

### ISSUE THREAD

**Issue by dreamtale90** [objectcomputing/OpenDDS#778]
I have a question about IDL. If I‘m not sure what type of data is sent (may be dynamic), what should I do?

**Comment by mitza-oci** [comment]
There are a few things to consider:
First, define a key field or fields: DDS works with a key in order to establish identity of data objects called "instances".  The key is often an integer or string, but more complex keys are possible too.
Then, determine how to represent dynamic data in IDL.  A few common patterns for this are to use a union like NameValuePair in $DDS_ROOT/dds/monitor/monitor.idl (your union can contain more types), or to use DDS::OctetSeq for binary data or just string for text.
Aside from the key, DDS only uses the schema of your data to implement content subscription features.

**Comment by dreamtale90** [comment]
OK, I see.
