### ISSUE TITLE
Compiling Error using RaspberryPi tool chain

### ISSUE THREAD

**Issue by SyedAliZafar** [objectcomputing/OpenDDS#816]
i was trying to cross compile my OpenDDS software through Raspberry Pi tool but i keep getting errors while running the make command
i ran configure command which had no errors
**syedli@ubuntu:~/Desktop/OpenDDS-3.12$

>  ./configure --target=linux-cross --target-compiler=$/home/syedli/Desktop/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++

But when i ran make command
syedli@ubuntu:~ make
i got the following errors
[CRosscompiling Error.txt](https://github.com/objectcomputing/OpenDDS/files/1753939/CRosscompiling.Error.txt)

**Comment by iguessthislldo** [comment]
Try removing the dollar sign from the configure command and run it again.

**Comment by SyedAliZafar** [comment]
i tried that also but the same error is occuring :(

**Comment by iguessthislldo** [comment]
Based the errors file it looks like you ran something like `./configure --target=linux-cross --target-compiler=</home/syedli/Desktop/tools-master>/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++` the first time and then tried to run the correct one after that. Unfortunately the configure script doesn't handle that being run multiple times well and in this case is keeping the first mistake instead of taking the correct one.

To fix this you need to basically start over, either by using `git clean -fdx` if you used git to download OpenDDS or removing OpenDDS and reextract it from the tar.gz if you downloaded it from opendds.org.

After that run `./configure --target=linux-cross --target-compiler=/home/syedli/Desktop/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++` and `make`.

**Comment by SyedAliZafar** [comment]
Great ! i would never have guessed ... thanks it worked :)
