### ISSUE TITLE
FACE/SingleProcessMessenger test failures

### ISSUE THREAD

**Issue by mitza-oci** [objectcomputing/OpenDDS#833]
Some builds are showing an error when running the "callback" form of this test:
```
Publisher: about to Send_Message()
Subscriber: about to Register_Callback()
ERROR: number callbacks seen incorrect (seen: 0 expected: 2)
ERROR: unexpected value in connection parameters after receiving
2018-04-03 11:48:25: ERROR: SingleProcess returned 1 (started at 2018-04-03 11:48:04)
test FAILED.
Error: tests/FACE/SingleProcessMessenger/run_test.pl callback returned with status 256
```
This test was added in #819, @kpansky please investigate and let me know if you need more info.

**Comment by kpansky** [comment]
I suspect this is a race condition in calling set_listener on the DataReader from Register_Callback and Send_Message triggering the DataReader listener.  I modified the test to setup callbacks prior to sending data, though I have not been able to replicate the failure on my setup so the fix is purely speculative.

**Comment by mitza-oci** [comment]
Opening issue until scoreboard results are available.
