### ISSUE TITLE
Add support for external google test library

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#910]
Currently google test is a git submodule and is expected always on the same place. For having more flexibility it would help when google test can be placed also in another place, for example at the same level as OpenDDS so that it can be used by OpenDDS but also other application parts. As user I could would like to set a GTEST_DIR to point to my google test installation and let OpenDDS use that.

**Comment by mitza-oci** [comment]
This will be part of the upcoming release's configure script.  It will also include .mpb file changes.

**Comment by mitza-oci** [comment]
See #916

**Comment by jwillemsen** [comment]
Looks the recent made changes did break our builds, going to checkout gtest separately and pre compile it in its own tree outside of OpenDDS

**Comment by mitza-oci** [comment]
See #917

**Comment by jwillemsen** [comment]
Our builds now checkout google test separate and compile it outside of the OpenDDS tree, $GTEST_ROOT is pointing to the that directory

**Comment by jwillemsen** [comment]
When cloning gtest I get googletest/googlemoch as first directory level, looks the MPC files ignore that, they add $GTEST_ROOT/include to the include path but shouldn't that be $GTEST_ROOT/googletest/include?

**Comment by mmcparlane** [comment]
With the new installation steps in [gtest_setup.txt](https://github.com/objectcomputing/OpenDDS/blob/master/tests/gtest_setup.txt), the new cmake commands add an install prefix, followed by the next cmake command which does the install into the specified directory. As such, the $GTEST_ROOT/include is based on the _installed_ version now instead of the _source_ tree. This provides better compatibility with, say, a version pulled down with "apt-get", "dnf" or otherwise.

**Comment by jwillemsen** [comment]
Updated our scripts, rebuilding again

**Comment by jwillemsen** [comment]
Looks googletest 1.8 doesn't compile at all with mingw64

**Comment by mitza-oci** [comment]
I was able to build googletest 1.8 using the MinGW compiler by adding -Dgtest_disable_pthreads=1 to cmake.
