### ISSUE TITLE
DomainParticipantImpl::contains_entity returns false for a newly created datareader

### ISSUE THREAD

**Issue by jmmorato** [objectcomputing/OpenDDS#941]
The `SubscriberImpl::contains_reader` is using the `datareader_set_` to check for the contained readers. Better to use the  `datareader_map_` for that purpose. Something like:

```
bool
SubscriberImpl::contains_reader(DDS::InstanceHandle_t a_handle)
{
  ACE_GUARD_RETURN(ACE_Recursive_Thread_Mutex,
                   guard,
                   this->si_lock_,
                   false);

  for (DataReaderMap::iterator it(datareader_map_.begin());
      it != datareader_map_.end(); ++it) {
    if (a_handle == it->second->get_instance_handle()) {
      return true;
    }
  }

  return false;
}
```

In any case, the datareader is only insterted in the `datareader_set_` on `data_received`. Shouldn't be added in the `reader_enabled` method instead?

**Comment by mitza-oci** [comment]
I agree that it appears to be broken since first added in 2009.  Please add a test.

As for the internals, let's keep datareader_set_ devoted to supporting get_datareaders and its interaction with Presentation QoS.  Perhaps it should have a different name, since it's not clear from datareader_set_ how it's used.  It also doesn't look like it's being cleared out at the right time (end_access, take, others?).
