### ISSUE TITLE
Visual Studio /clr leads to linking errors

### ISSUE THREAD

**Issue by floatingbit** [objectcomputing/OpenDDS#962]
Hi,

I am not clear whether .NET is supported by OpenDDS. According to the article https://objectcomputing.com/resources/publications/mnb/using-tao-and-opendds-with-net-part-1, we should be able to set the mpc attribute "managed = 1" which gives me multiple linking errors with the following message:

unresolved token (0A000B4E) "private: void __cdecl OpenDDS::DCPS::DataReaderImpl::LivelinessTimer::check_liveliness_i(bool,class ACE_Time_Value const &)" (?check_liveliness_i@LivelinessTimer@DataReaderImpl@DCPS@OpenDDS@@$$FAEAAX_NAEBVACE_Time_Value@@@Z) referenced in function "public: virtual void __cdecl OpenDDS::DCPS::DataReaderImpl::LivelinessTimer::CheckLivelinessCommand::execute(void)" (?execute@CheckLivelinessCommand@LivelinessTimer@DataReaderImpl@DCPS@OpenDDS@@$$FUEAAXXZ)

Please advise as I am trying to access .NET /clr projects from OpenDDS VC++ projects.

**Comment by mitza-oci** [comment]
The articles is from a long time ago, I think if you'd try an OpenDDS version from that time frame it would probably work.  Not that I'm recommending using an old OpenDDS.

Please take a look at https://github.com/jmmorato/openddsharp and see how this issue is handled there.

**Comment by floatingbit** [comment]
I'll take a look, thank you for your feedback!

**Comment by jmmorato** [comment]
Take a look to the Patches folder. 

Better if you use the tag v0.2.1 because in the current version also includes some fixes that has been already intengrated in OpenDDS. From tag v0.2.1, you will need the Patches DataReaderImpl.*.patch and unique_ptr.h.patch.

However, it would be nice if you give a try to the openddsharp project ;)

**Comment by floatingbit** [comment]
@jmmorato Testing it out already :)

I am having trouble getting your project up and running. Any chance you can share a README with a basic outline of steps on how to use your library?

**Comment by jmmorato** [comment]
This is the ticket I have to document the build project:
https://github.com/jmmorato/openddsharp/issues/13

There you can found basic steps to build the project.

I plan to correctly document it and test it in a clean machine, but right now better to use the Nuget packages, especially for the IDL code generation part. 

You can read a "getting started" tutorial here:
http://openddsharp.com/Documentation/GetStarted

I know that documentation is not good enough but I'm working in testing the API (currently ~75% covered) and finishing up the current C++/CLI version. I also plan a P/Invoke version in order to allow .net core, xamarin, unity 3d... 

Any collaboration to the project would be welcome :)

**Comment by mitza-oci** [comment]
Is it to the point where we should look at integrating more of the Patches upstream?  Should be easier to verify with CI now that Azure Pipelines builds are enabled.

**Comment by jmmorato** [comment]
yeah, I'll pull request them separately and see how they behave in the azure pipeline
